title: "Archi Jain"
email: archij30@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: "/" 
url: "https://archij30.github.io" 
twitter_username: 
github_username: archij30

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
